services:
  - type: web
    name: voting-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://abc:93565227@vote.2zj2mng.mongodb.net/
